### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by butcheryl** [ergunemr/BottomPopup#6] opened 2018-10-22 07:26 UTC
https://github.com/ergunemr/BottomPopup/blob/886c3ba4776bfa52674886a968192c3719128adc/BottomPopup/BottomPopupController/BottomPopupViewController.swift#L17

```
override public init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) { 
```

**Comment by ergunemr** [comment] 2018-10-23 08:07
Duplicate of #5

**Closed by ergunemr** 2018-10-23 08:07 UTC
